version: "3.8"

services:
  postgres:
    image: "postgres:10"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
#    command: ["postgres", "-c", "log_statement=all"]